# Generated by Django 5.2.2 on 2026-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('wanderer', 'Wanderer'), ('founder', 'Founder'), ('ascendant', 'Ascendant'), ('phantom', 'Phantom'), ('eclipse', 'Eclipse'), ('eternal', 'Eternal')], default='wanderer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='unlocked_arcs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
