# Generated by Django 6.0.4 on 2026-05-10 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0003_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMapProgress',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_maps_collected', models.PositiveIntegerField(default=0)),
                ('unique_maps_collected', models.PositiveIntegerField(default=0)),
                ('total_rewards_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_completed_all', models.BooleanField(default=False)),
                ('final_reward_claimed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_map_progress',
            },
        ),
        migrations.CreateModel(
            name='TreasureMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('map_type', models.CharField(choices=[('map_1', 'Golden Desert'), ('map_2', 'Crystal Ocean'), ('map_3', 'Emerald Forest'), ('map_4', 'Ruby Mountain'), ('map_5', 'Sapphire Sky'), ('map_6', 'Amber Valley'), ('map_7', 'Pearl Beach'), ('map_8', 'Diamond Peak'), ('map_9', 'Jungle Mystery'), ('map_10', 'Arctic Treasure'), ('map_11', 'Volcano Gold'), ('map_12', 'Final Kingdom')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='maps/')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_released', models.BooleanField(default=False)),
                ('release_trigger_sales', models.PositiveIntegerField(default=100)),
                ('full_set_prize', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('partial_prize_min_maps', models.PositiveIntegerField(default=3)),
                ('partial_prize_amount', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'treasure_maps',
                'ordering': ['map_type'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMapClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('verified', 'Verified'), ('rewarded', 'Rewarded'), ('expired', 'Expired')], default='claimed', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_claims', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_claims', to='orders.order')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='orders.treasuremap')),
            ],
            options={
                'db_table': 'customer_map_claims',
                'ordering': ['-claimed_at'],
                'unique_together': {('customer', 'map')},
            },
        ),
    ]
