# Generated by Django 5.2.2 on 2026-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customermapprogress_treasuremap_customermapclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arc_unlock_processed',
            field=models.BooleanField(default=False),
        ),
    ]
