# Generated by Django 5.2.2 on 2026-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_rank_user_unlocked_arcs_user_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('wanderer', 'Wanderer'), ('founder', 'Founder'), ('ascendant', 'Ascendant'), ('phantom', 'Phantom'), ('eclipse', 'Eclipse'), ('crimson', 'Crimson'), ('void', 'Void'), ('zenith', 'Zenith'), ('cosmic', 'Cosmic'), ('shadow_war', 'Shadow War'), ('celestial', 'Celestial'), ('eternal', 'Eternal')], default='wanderer', max_length=20),
        ),
    ]
