# Generated by Django 6.0.4 on 2026-05-12 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='hero_banners/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='hero_banners/mobile/')),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_link', models.CharField(default='/products', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
