# Generated by Django 5.2.2 on 2026-05-20 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='image_url_direct',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='mobile_image_url_direct',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_banners/mobile/'),
        ),
        migrations.AlterModelTable(
            name='herobanner',
            table='hero_banners',
        ),
    ]
