# Generated by Django 6.0.4 on 2026-05-17 16:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0002_qroffer_qrscanlog'),
        ('orders', '0002_customermapprogress_treasuremap_customermapclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Clock Tower'), (2, 'Level 2 - Marina Beach'), (3, 'Level 3 - Temple Street'), (4, 'Level 4 - Tech Park'), (5, 'Level 5 - Final Treasure')], unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(max_length=100)),
                ('clue_text_tamil', models.TextField()),
                ('clue_text_english', models.TextField()),
                ('hint_image_url', models.URLField(blank=True, null=True)),
                ('geo_lat', models.DecimalField(decimal_places=8, help_text='Latitude of the location', max_digits=10)),
                ('geo_long', models.DecimalField(decimal_places=8, help_text='Longitude of the location', max_digits=11)),
                ('geo_radius_meters', models.PositiveIntegerField(default=100, help_text='Allowed radius in meters for GPS validation')),
                ('location_qr_secret', models.CharField(help_text='Secret code on the physical QR sticker at this location', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_coupon_template', models.ForeignKey(blank=True, help_text='Coupon template to clone when user reaches this level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_locations', to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Hunt Location',
                'verbose_name_plural': 'Hunt Locations',
                'db_table': 'hunt_locations',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TShirtQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(db_index=True, help_text='Unique secret embedded in QR code (e.g., th-xyz123abc)', max_length=64, unique=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_qrs', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Linked order that purchased the T-shirt', on_delete=django.db.models.deletion.CASCADE, related_name='tshirt_qr', to='orders.order')),
            ],
            options={
                'verbose_name': 'T-Shirt QR Code',
                'verbose_name_plural': 'T-Shirt QR Codes',
                'db_table': 'tshirt_qrcodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserHuntProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_level', models.PositiveSmallIntegerField(default=0, help_text='0=Not started, 1-5=Current active level, 6=Completed', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_minutes', models.PositiveIntegerField(default=0, help_text='Total hunt duration')),
                ('tshirt_qr', models.OneToOneField(help_text='The T-shirt QR that activated this hunt', on_delete=django.db.models.deletion.CASCADE, related_name='hunt_progress', to='treasurehunt.tshirtqrcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Hunt Progress',
                'verbose_name_plural': 'User Hunt Progress',
                'db_table': 'user_hunt_progress',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0, help_text='Score based on levels completed and speed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_leaderboard', to=settings.AUTH_USER_MODEL)),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='treasurehunt.userhuntprogress')),
            ],
            options={
                'verbose_name': 'Hunt Leaderboard',
                'verbose_name_plural': 'Hunt Leaderboard',
                'db_table': 'hunt_leaderboard',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='HuntReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_rewards', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_rewards', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='treasurehunt.userhuntprogress')),
            ],
            options={
                'verbose_name': 'Hunt Reward',
                'verbose_name_plural': 'Hunt Rewards',
                'db_table': 'hunt_rewards',
                'ordering': ['-claimed_at'],
                'unique_together': {('progress', 'level')},
            },
        ),
    ]
