# Generated by Django 5.2.2 on 2026-05-23 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arc_number', models.PositiveIntegerField(help_text='1-12', unique=True)),
                ('arc_key', models.CharField(choices=[('founder', "Founder's Arc"), ('phantom', 'Phantom Arc'), ('ascension', 'Ascension Arc'), ('rebirth', 'Rebirth Arc'), ('eclipse', 'Eclipse Arc'), ('crimson', 'Crimson Arc'), ('void', 'Void Arc'), ('zenith', 'Zenith Arc'), ('cosmic', 'Cosmic Arc'), ('shadow_war', 'Shadow War Arc'), ('celestial', 'Celestial Arc'), ('eternal', 'Eternal Arc')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('theme_color', models.CharField(default='#FFD700', max_length=7)),
                ('map_x', models.FloatField(help_text='X position on map (0-100)')),
                ('map_y', models.FloatField(help_text='Y position on map (0-100)')),
                ('island_icon', models.CharField(choices=[('island', 'Island'), ('volcano', 'Volcano'), ('fortress', 'Fortress'), ('void', 'Void'), ('castle', 'Castle'), ('cosmic', 'Cosmic'), ('celestial', 'Celestial'), ('storm', 'Storm')], default='island', max_length=50)),
                ('island_size', models.FloatField(default=1.0, help_text='Scale factor')),
                ('lore_summary', models.TextField()),
                ('lore_full', models.TextField(blank=True)),
                ('hero_name', models.CharField(blank=True, max_length=100)),
                ('hero_description', models.TextField(blank=True)),
                ('unlock_type', models.CharField(choices=[('rank', 'Rank Based'), ('community', 'Community Sales Target'), ('time', 'Time Based'), ('secret', 'Secret Hunt'), ('purchase', 'Purchase Previous Arc')], default='rank', max_length=20)),
                ('required_rank', models.CharField(default='wanderer', max_length=20)),
                ('sales_target', models.PositiveIntegerField(default=0, help_text='Community sales to unlock')),
                ('unlock_date', models.DateTimeField(blank=True, null=True)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_revealed', models.BooleanField(default=False, help_text='Visible but locked (fog)')),
                ('ambient_effect', models.CharField(choices=[('none', 'None'), ('fog', 'Fog/Mist'), ('fire', 'Fire/Volcano'), ('stars', 'Stars/Cosmic'), ('storm', 'Storm'), ('glow', 'Golden Glow'), ('darkness', 'Void Darkness')], default='none', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='arcs', to='products.product')),
            ],
            options={
                'db_table': 'arcs',
                'ordering': ['arc_number'],
            },
        ),
        migrations.CreateModel(
            name='CommunityUnlockProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_sales', models.PositiveIntegerField(default=0)),
                ('sales_target', models.PositiveIntegerField(default=1000)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('milestone_25', models.BooleanField(default=False)),
                ('milestone_50', models.BooleanField(default=False)),
                ('milestone_75', models.BooleanField(default=False)),
                ('milestone_90', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_progress', to='treasurehunt.arc')),
            ],
            options={
                'db_table': 'community_unlock_progress',
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('treasure_type', models.CharField(choices=[('discount', 'Discount Code'), ('lore', 'Lore Fragment'), ('badge', 'Founder Badge'), ('product', 'Secret Product'), ('xp', 'XP Boost'), ('rank', 'Rank Skip'), ('clue', 'Next Arc Clue')], max_length=20)),
                ('description', models.TextField()),
                ('map_x', models.FloatField()),
                ('map_y', models.FloatField()),
                ('clue_text', models.TextField(help_text='Hint to find this treasure')),
                ('secret_code', models.CharField(blank=True, help_text='Code to unlock', max_length=100)),
                ('reward_value', models.CharField(blank=True, help_text="e.g., '20% off' or '500 XP'", max_length=200)),
                ('reward_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('max_claims', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasures', to='treasurehunt.arc')),
            ],
            options={
                'db_table': 'treasures',
                'ordering': ['arc', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FounderProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_distance_traveled', models.FloatField(default=0, help_text='Total path distance')),
                ('secrets_found', models.PositiveIntegerField(default=0)),
                ('last_login_scene', models.CharField(choices=[('map', 'World Map'), ('arc', 'Arc Detail'), ('treasure', 'Treasure Found'), ('lore', 'Lore Discovery')], default='map', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_explorers', to='treasurehunt.arc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_progress', to=settings.AUTH_USER_MODEL)),
                ('visited_arcs', models.ManyToManyField(blank=True, related_name='visitors', to='treasurehunt.arc')),
                ('discovered_treasures', models.ManyToManyField(blank=True, related_name='discovered_by', to='treasurehunt.treasure')),
            ],
            options={
                'db_table': 'founder_progress',
            },
        ),
        migrations.CreateModel(
            name='ShipPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_data', models.TextField(help_text='SVG path d attribute')),
                ('animation_duration', models.FloatField(default=2.0, help_text='Seconds to travel')),
                ('path_style', models.CharField(choices=[('dotted', 'Dotted Line'), ('dashed', 'Dashed Line'), ('glowing', 'Glowing Path'), ('hidden', 'Hidden/Undiscovered')], default='dotted', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('from_arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_from', to='treasurehunt.arc')),
                ('to_arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_to', to='treasurehunt.arc')),
            ],
            options={
                'db_table': 'ship_paths',
                'unique_together': {('from_arc', 'to_arc')},
            },
        ),
        migrations.CreateModel(
            name='TreasureClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='treasurehunt.treasure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treasure_claims',
                'unique_together': {('treasure', 'user')},
            },
        ),
    ]
