# Generated by Django 5.2.2 on 2026-05-24 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_qroffer_qrscanlog'),
        ('orders', '0003_order_arc_unlock_processed'),
        ('treasurehunt', '0002_huntlocation_alter_arc_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # === ADD MISSING FIELDS TO EXISTING MODELS ===
        
        # Arc model - missing fields
        migrations.RunSQL(
    "SELECT 1;",  # do nothing if exists
    reverse_sql="SELECT 1;",
),
        migrations.AddField(
            model_name='arc',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arc',
            name='unlock_secret_code',
            field=models.CharField(blank=True, help_text='Secret code to unlock this arc', max_length=100),
        ),
        migrations.AddField(
            model_name='arc',
            name='unlock_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Number of purchases needed for community unlock'),
        ),
        
        # CommunityUnlockProgress - missing fields
        migrations.AddField(
            model_name='communityunlockprogress',
            name='contributing_users',
            field=models.JSONField(default=list, help_text='List of user IDs who contributed'),
        ),
        migrations.AddField(
            model_name='communityunlockprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityunlockprogress',
            name='current_purchases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityunlockprogress',
            name='target_purchases',
            field=models.PositiveIntegerField(default=100),
        ),
        
        # Treasure - missing fields
        migrations.AddField(
            model_name='treasure',
            name='icon',
            field=models.CharField(default='💎', max_length=10),
        ),
        migrations.AddField(
            model_name='treasure',
            name='xp_reward',
            field=models.PositiveIntegerField(default=50),
        ),
        
        # === ALTER EXISTING FIELDS ===
        
        migrations.AlterField(
            model_name='arc',
            name='arc_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='arc',
            name='island_size',
            field=models.FloatField(default=1.0, help_text='Scale factor', validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='arc',
            name='lore_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='arc',
            name='map_x',
            field=models.FloatField(help_text='X position on map (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='arc',
            name='map_y',
            field=models.FloatField(help_text='Y position on map (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='arc',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='arc',
            name='unlock_type',
            field=models.CharField(choices=[('auto', 'Auto (previous completed)'), ('rank', 'Rank Based'), ('community', 'Community Sales Target'), ('time', 'Time Based'), ('secret', 'Secret Hunt'), ('purchase', 'Purchase Previous Arc')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='communityunlockprogress',
            name='arc',
            field=models.OneToOneField(limit_choices_to={'unlock_type': 'community'}, on_delete=django.db.models.deletion.CASCADE, related_name='community_progress', to='treasurehunt.arc'),
        ),
        migrations.AlterField(
            model_name='shippath',
            name='path_data',
            field=models.TextField(blank=True, help_text='SVG path d attribute'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='arc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasures', to='treasurehunt.arc'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='clue_text',
            field=models.TextField(blank=True, help_text='Hint to find this treasure'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='map_x',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='map_y',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        
        # === CREATE NEW MODELS (that don't exist yet) ===
        
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('arc_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='treasurehunt.communityunlockprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfinity_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Log',
                'verbose_name_plural': 'Purchase Logs',
                'db_table': 'purchase_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reward_type', models.CharField(choices=[('badge', 'Badge'), ('theme', 'UI Theme'), ('xp_boost', 'XP Boost'), ('discount', 'Discount Code'), ('product', 'Product Unlock'), ('title', 'Title/Rank')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎁', max_length=10)),
                ('discount_percentage', models.PositiveSmallIntegerField(default=0)),
                ('discount_code', models.CharField(blank=True, max_length=50)),
                ('xp_multiplier', models.FloatField(default=1.0)),
                ('xp_boost_duration_days', models.PositiveSmallIntegerField(default=3)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='treasurehunt.arc')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'db_table': 'rewards',
                'ordering': ['arc'],
            },
        ),
        migrations.CreateModel(
            name='StorySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='story_images/')),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_segments', to='treasurehunt.arc')),
            ],
            options={
                'verbose_name': 'Story Segment',
                'verbose_name_plural': 'Story Segments',
                'db_table': 'story_segments',
                'ordering': ['arc', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TShirtQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_qrs', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tshirt_qr', to='orders.order')),
            ],
            options={
                'db_table': 'tshirt_qrcodes',
            },
        ),
        migrations.CreateModel(
            name='UserHuntProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('tshirt_qr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_progress', to='treasurehunt.tshirtqrcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_hunt_progress',
            },
        ),
        migrations.CreateModel(
            name='HuntLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_leaderboard', to=settings.AUTH_USER_MODEL)),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='treasurehunt.userhuntprogress')),
            ],
            options={
                'db_table': 'hunt_leaderboard',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_key', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('reflection', 'Reflection'), ('purchase', 'Purchase'), ('community', 'Community Join'), ('streak', 'Daily Streak'), ('share', 'Social Share'), ('secret', 'Secret Find'), ('quiz', 'Quiz')], max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('required_streak_days', models.PositiveSmallIntegerField(default=7)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='treasurehunt.arc')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenges',
                'ordering': ['arc', 'order'],
                'unique_together': {('arc', 'challenge_key')},
            },
        ),
        migrations.CreateModel(
            name='HuntReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_rewards', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='treasurehunt.userhuntprogress')),
            ],
            options={
                'db_table': 'hunt_rewards',
                'unique_together': {('progress', 'level')},
            },
        ),
    ]