# Generated by Django 5.2.2 on 2026-05-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0003_add_missing_fields'),
    ]

    operations = [
    ]
