# Generated by Django 5.2.2 on 2026-05-25 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0004_add_missing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userhuntprogress',
            name='unlocked_arcs',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='MysteryCardQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('reward_type', models.CharField(choices=[('arc', 'Unlock Story Arc'), ('coupon', 'Discount Coupon')], max_length=10)),
                ('arc_slug', models.CharField(blank=True, help_text='Example: wanderer, founderer', max_length=50, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
