# Generated by Django 5.2.2 on 2026-05-26 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0005_userhuntprogress_unlocked_arcs_mysterycardqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhuntprogress',
            name='tshirt_qr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunt_progress', to='treasurehunt.tshirtqrcode'),
        ),
    ]
