# Generated by Django 5.2.2 on 2026-05-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='image_url_direct',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='mobile_image_url_direct',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
