# Generated by Django 5.2.2 on 2026-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order Update'), ('promo', 'Promotion'), ('system', 'System'), ('support', 'Support Reply'), ('rank_up', 'Rank Up')], default='system', max_length=20),
        ),
    ]
