# Generated by Django 6.0.4 on 2026-05-10 10:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QROffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('qr_code_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('reveal_type', models.CharField(choices=[('fixed', 'Fixed Discount'), ('random', 'Random Discount'), ('spin', 'Spin Wheel'), ('scratch', 'Scratch Card')], default='random', max_length=10)),
                ('min_discount', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('max_discount', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('fixed_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('max_scans', models.PositiveIntegerField(default=100)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('scan_expiry_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_offers', to='coupons.coupon')),
            ],
            options={
                'db_table': 'qr_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('discount_revealed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qr_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='coupons.qroffer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qr_scan_logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
