# Generated by Django 6.0.4 on 2026-05-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_search_vector_product_tags_and_more'),
    ]

    operations = [
    ]
