# Generated by Django 5.2.2 on 2026-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20260515_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arc_type',
            field=models.CharField(choices=[('founder', 'Founder Edition'), ('ascendant', 'Ascension Edition'), ('phantom', 'Phantom Arc'), ('eclipse', 'Eclipse Edition'), ('eternal', 'Eternal Edition')], default='founder', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='drop_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drop_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_limited_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='lore_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='required_rank',
            field=models.CharField(default='wanderer', max_length=20),
        ),
    ]
