# Generated by Django 5.2.2 on 2026-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_arc_type_product_drop_end_product_drop_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arc_type',
            field=models.CharField(choices=[('wanderer', 'Wanderer'), ('founder', 'Founder Edition'), ('ascendant', 'Ascension Edition'), ('phantom', 'Phantom Arc'), ('eclipse', 'Eclipse Edition'), ('eternal', 'Eternal Edition')], default='founder', max_length=20),
        ),
    ]
